// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpsteabvbzbnjdhqjakf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwc3RlYWJ2YnpibmpkaHFqYWtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NzQxMjEsImV4cCI6MjA1OTM1MDEyMX0.XLFlz7qVd-R8fkpItehz_9M0Mh3kj62B-96wo_JoZc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);